const { test } = require('node:test');
const assert = require('node:assert/strict');
const { extractTextFromFile, extractFromCaptions } = require('../../src/utils/text-extractors');

test('WebVTT: keeps speaker names, drops header, notes, timings and repeated cues', () => {
  const vtt = [
    '﻿WEBVTT',
    '',
    'NOTE generated by Meet',
    '',
    '1',
    '00:00:01.000 --> 00:00:03.000 align:start',
    '<v Ana Lopez>We will ship on Friday.</v>',
    '',
    '00:00:03.000 --> 00:00:05.000',
    '<v.loud Bob>Agreed, <b>Friday</b>.',
    '',
    '00:00:05.000 --> 00:00:06.000',
    '<v.loud Bob>Agreed, <b>Friday</b>.'
  ].join('\n');

  const result = extractFromCaptions(Buffer.from(vtt));
  assert.equal(result.success, true);
  assert.equal(result.text, 'Ana Lopez: We will ship on Friday.\nBob: Agreed, Friday.');
});

test('SRT: handles CRLF and keeps spoken lines that are only numbers', () => {
  const srt = '1\r\n00:00:01,000 --> 00:00:03,000\r\nHello team\r\n\r\n2\r\n00:00:03,000 --> 00:00:04,000\r\n42\r\n';
  const result = extractFromCaptions(Buffer.from(srt));
  assert.equal(result.text, 'Hello team\n42');
});

test('extractTextFromFile dispatches by extension, even with a misleading MIME type', async () => {
  const srt = '1\n00:00:01,000 --> 00:00:02,000\nHi\n';
  const result = await extractTextFromFile(Buffer.from(srt), 'meeting.srt', 'text/plain');
  assert.equal(result.text, 'Hi');

  const md = await extractTextFromFile(Buffer.from('# Notes'), 'notes.md', 'application/octet-stream');
  assert.equal(md.text, '# Notes');
});

test('extractTextFromFile rejects unsupported types with a helpful message', async () => {
  const result = await extractTextFromFile(Buffer.from('x'), 'old.doc', 'application/msword');
  assert.equal(result.success, false);
  assert.match(result.error, /Supported: .txt, .md, .vtt, .srt, .pdf, .docx/);
});
