const { test } = require('node:test');
const assert = require('node:assert/strict');
const { extractTextFromFile, extractFromCaptions } = require('../../src/utils/text-extractors');

test('WebVTT: keeps speaker names, drops header, notes, timings and repeated cues', () => {
  const vtt = [
    '﻿WEBVTT',
    '',
    'NOTE generated by Meet',
    '',
    '1',
    '00:00:01.000 --> 00:00:03.000 align:start',
    '<v Ana Lopez>We will ship on Friday.</v>',
    '',
    '00:00:03.000 --> 00:00:05.000',
    '<v.loud Bob>Agreed, <b>Friday</b>.',
    '',
    '00:00:05.000 --> 00:00:06.000',
    '<v.loud Bob>Agreed, <b>Friday</b>.'
  ].join('\n');

  const result = extractFromCaptions(Buffer.from(vtt));
  assert.equal(result.success, true);
  assert.equal(result.text, 'Ana Lopez: We will ship on Friday.\nBob: Agreed, Friday.');
});

test('SRT: handles CRLF and keeps spoken lines that are only numbers', () => {
  const srt = '1\r\n00:00:01,000 --> 00:00:03,000\r\nHello team\r\n\r\n2\r\n00:00:03,000 --> 00:00:04,000\r\n42\r\n';
  const result = extractFromCaptions(Buffer.from(srt));
  assert.equal(result.text, 'Hello team\n42');
});

test('extractTextFromFile dispatches by extension, even with a misleading MIME type', async () => {
  const srt = '1\n00:00:01,000 --> 00:00:02,000\nHi\n';
  const result = await extractTextFromFile(Buffer.from(srt), 'meeting.srt', 'text/plain');
  assert.equal(result.text, 'Hi');

  const md = await extractTextFromFile(Buffer.from('# Notes'), 'notes.md', 'application/octet-stream');
  assert.equal(md.text, '# Notes');
});

test('extractTextFromFile rejects unsupported types with a helpful message', async () => {
  const result = await extractTextFromFile(Buffer.from('x'), 'old.doc', 'application/msword');
  assert.equal(result.success, false);
  assert.match(result.error, /Supported: .txt, .md, .vtt, .srt, .pdf, .docx/);
});

/** A one-page PDF with a line of text (Helvetica), built by hand */
function tinyPdf(text) {
  const content = `BT /F1 24 Tf 72 700 Td (${text}) Tj ET`;
  const bodies = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'
  ];
  let pdf = '%PDF-1.4\n';
  const offsets = bodies.map((body, i) => {
    const offset = pdf.length;
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
    return offset;
  });
  const xref = pdf.length;
  pdf += `xref\n0 6\n0000000000 65535 f \n${offsets.map(o => `${String(o).padStart(10, '0')} 00000 n \n`).join('')}`;
  pdf += `trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(pdf, 'latin1');
}

test('PDF: text comes out (pdf-parse v2), without page markers', async () => {
  const result = await extractTextFromFile(tinyPdf('Se decide lanzar en octubre'), 'notes.pdf');
  assert.equal(result.success, true, result.error);
  assert.match(result.text, /Se decide lanzar en octubre/);
  assert.doesNotMatch(result.text, /-- 1 of 1 --/);
});
